version: '3'
services:
  orchestrator-backend:
    build: ./orchestrator-backend
    container_name: orchestrator
    ports:
      - "2222:2222" # WebSocket port
    networks:
      orchestrator-network:
        ipv4_address: 172.30.0.10
    environment:
      - SHARED_PORT=2222
      #volumes:
      #Not used for now
      #- ./orchestrator-backend/config/vpn-config.json:/orchestrator-backend/config/vpn-config.json # Mount VPN config file
      # - ./orchestrator-backend/config/orchestrator-config.json:/orchestrator-backend/config/orchestrator-config.json # Mount orchestrator config

  orchestrator-frontend:
    build:
      context: ./orchestrator-frontend
      args:
        NEXT_PUBLIC_SOCKET_HOST: "http://orchestrator:2222/interfaces"
        NEXT_PUBLIC_UNREAL_DEFAULT_PORT: "8764"
        NEXT_PUBLIC_ORCHESTRATOR_BACKEND: "http://orchestrator:2222/configurations"
    container_name: orchestrator-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_SOCKET_HOST=http://orchestrator:2222/interfaces
      - NEXT_PUBLIC_UNREAL_DEFAULT_PORT=8764
      - NEXT_PUBLIC_ORCHESTRATOR_BACKEND=http://orchestrator:2222/configurations
    networks:
      - orchestrator-network

networks:
  orchestrator-network:
    external: true
    ipam:
      config:
        - subnet: 172.30.0.0/16
