version: '3'
services:
  orchestrator-backend:
    build: ./orchestrator-backend
    ports:
      - "4444:2222" # WebSocket port
    networks:
      - XR-IT-network
    environment:
      - SHARED_PORT=2222
      - NODE_BACKEND_HOST=node-backend
    volumes:
      #Not used for now
      - ./orchestrator-backend/config/vpn-config.json:/orchestrator-backend/config/vpn-config.json # Mount VPN config file
      - ./orchestrator-backend/config/orchestrator-config.json:/orchestrator-backend/config/orchestrator-config.json # Mount orchestrator config

  node-backend:
    build: ./node-backend
    ports:
      - "4242:2222" # WebSocket port
    networks:
      - XR-IT-network
    environment:
      - SHARED_PORT=2222
      - ORCHESTRATOR_BACKEND_HOST=orchestrator-backend
    volumes:
      #Not used for now
      - ./node-backend/config/client-vpn-config.json:/node-backend/config/client-vpn-config.json # Mount VPN config file  

  # SoftEther VPN Client
  vpn-client:
    image: containinger/docker-softether-vpn-client:latest
    container_name: vpn-client
    privileged: true
    cap_add:
      - NET_ADMIN
    environment:
      - SE_SERVER=10.10.10.1/tcp:5555 # Update with your VPN server details
      - SE_HUB=XRIT # Update with your VPN hub
      - SE_USERNAME=arkan # Update with your VPN username
      - SE_PASSWORD=vmT7JJNX8WjBCDrt # Update with your VPN password
    networks:
      - XR-IT-network

networks:
  XR-IT-network:
    driver: bridge
